### ISSUE TITLE
Wordnet 'index.sense' file name automatically set to 'sense.idx'	

### ISSUE THREAD

**Issue by zesch** [dkpro/dkpro-lsr#1]
Originally reported by turkovic.mladen, Jul 7, 2014 on GoogleCode

In UkpFileManagerImpl.java 
line 108-111 

Resets WordNet "index.sense" file-name to "sense.idx"

 String sense = "index.sense";
 if (JWNL.getVersion().getNumber() < 2.1) {
            sense = "sense.idx";
 }

But all my WordNet (1.7, 2.1, 3.0, 3.1) installations in Unix (Ubuntu 12.04) have only "index.sense" files

This results in error when calling "LsrSenseInventoryResource"

-----------------------------------
Workaround:
Copy "index.sense" file in WordNet 1.7/dict and rename to "sense.idx"

-----------------------------------

The problem occurred with:
de.tudarmstadt.ukp.dkpro.wsd.examples-gpl / Senseval2EnLSExample.java

Running Ubuntu 12.04 (Eclipse Kepler Service Release 2)

**Comment by logological** [comment]
No need to fix this, as `UkpFileManagerImpl` has been removed as of DKPro LSR 0.8.1.
