### ISSUE TITLE
Migrate from JWNL to extJWNL 1.9

### ISSUE THREAD

**Issue by logological** [dkpro/dkpro-lsr#4]
DKPro LSR currently uses the ancient, buggy, and unmaintained JWNL.  Most modern NLP applications have moved to extJWNL, which is maintained.  Unfortunately, using both JWNL and extJWNL in the same project can lead to errors, so this limits the usability of DKPro LSR in other projects.

It would be nice if DKPro LSR were rewritten to use the latest version of extJWNL (1.9).

I've done a local rewrite myself.  The only classes which I was unable to migrate were `de.tudarmstadt.ukp.dkpro.lexsemresource.wordnet.util.UkpFileManagerImpl` and `de.tudarmstadt.ukp.dkpro.lexsemresource.wordnet.util.UkpRandomAccessDictionaryFile`.  I have no idea what these are for; they have no meaningful documentation and they're not referenced anywhere else in DKPro LSR, including in any unit tests.  Would it be OK if I simply removed these two classes?

**Comment by reckart** [comment]
Sounds like attempts to load the data from alternative places. I don't think these are of relevance anymore since extJWNL supports loading the resources from JARs (Maven dependencies).

**Comment by zesch** [comment]
I think @reckart is right. These files were special implementations of the classes references in the JWNL configuration file. If we switch to extJWNL anyway, we will not need them anymore.

**Comment by logological** [comment]
Duplicate of Issue #2.
